development:
  host: localhost
  database: ascii_development

test:
  host: localhost
  database: ascii_test

# set these environment variables on your prod server
production:
  host: <%= ENV['mongodb://superhappyfuntime:trever101@staff.mongohq.com:10061/ASCII
'] %>
  port: <%= ENV['10061'] %>
  username: <%= ENV['superhappyfuntime'] %>
  password: <%= ENV['trever101'] %>
  database: <%= ENV['ASCII'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
